// ============================================================
// COSMETICS — client render definitions for the #205 unlock catalog
// ============================================================
// The server owns WHAT exists / what's unlocked / what's equipped
// (engine/progression.js); this module owns only how each id LOOKS.
// Ids must match the server catalog exactly. Everything is plain CSS
// values (gradients + hexes) — no image assets — applied through CSS
// custom properties so the existing table styles pick them up with
// their current look as the fallback.

// ─── Gun / cylinder skins (SpinOverlay) ───────────────────────
// Keys mirror the hard-coded colors CylinderSVG used before #205;
// `gun_steel` IS that original palette.
export const GUN_SKINS = {
  gun_steel: {
    body: '#111118', bodyStroke: '#2a2a35',
    chamber: '#0d0d18', chamberStroke: '#333',
    hub: '#222230', hubStroke: '#444',
  },
  gun_brass: {
    body: '#1d1607', bodyStroke: '#8a6a24',
    chamber: '#171003', chamberStroke: '#9a7a2e',
    hub: '#3a2c10', hubStroke: '#c89a3e',
  },
  gun_obsidian: {
    body: '#0a0812', bodyStroke: '#4d3568',
    chamber: '#0c0716', chamberStroke: '#5b3f86',
    hub: '#1d1430', hubStroke: '#8a64c8',
  },
  gun_gilded: {
    body: '#241a05', bodyStroke: '#c8922e',
    chamber: '#1a1204', chamberStroke: '#e0b04f',
    hub: '#4a3408', hubStroke: '#f0c860',
  },
  // The five owner-art identities (matching the deck skins + table felts).
  // Palettes lifted from the deck designs; empty chambers stay darker than
  // the body and well away from the bullet reds (#3a0808/#882222) so the
  // chamber state — the game info — keeps its contrast on every skin.
  gun_noir: {
    body: '#0d0c11', bodyStroke: '#c8a35a',
    chamber: '#070609', chamberStroke: '#9a7438',
    hub: '#1d1a24', hubStroke: '#ecd28c',
  },
  gun_crimson: {
    body: '#4c1320', bodyStroke: '#c4a060',
    chamber: '#1a060c', chamberStroke: '#9c7a40',
    hub: '#6b1e2c', hubStroke: '#e6cd8e',
  },
  gun_neon: {
    body: '#141436', bodyStroke: '#45e6e6',
    chamber: '#0c0c26', chamberStroke: '#6a8af0',
    hub: '#1b1b42', hubStroke: '#e84dd0',
  },
  gun_kente: {
    body: '#8d4220', bodyStroke: '#e2a92e',
    chamber: '#1c150d', chamberStroke: '#e2a92e',
    hub: '#2f6b3a', hubStroke: '#e2a92e',
  },
  gun_cosmos: {
    body: '#0a0a14', bodyStroke: '#9a6ae8',
    chamber: '#06060c', chamberStroke: '#4a8ae0',
    hub: '#10101e', hubStroke: '#e88ad8',
  },
};

// ─── Deck skins (card backs + the player's own hand's card faces) ──
// `back_leather` is the original CSS-only leather look. The others carry a
// `frame`: a self-contained colored SVG (built from the owner-supplied frame
// art by client/scripts/build-cosmetic-decks.mjs, in public/cosmetics) that
// paints BOTH the face-down backs and, with the shape + number overlaid in
// its empty centre, this player's own hand cards. `accent` colours the
// filigree/glow accents wherever the skin shows.
export const CARD_BACKS = {
  back_leather: { a: '#1e1410', b: '#120d09', c: '#1a1108', accent: 'var(--accent)' },
  back_noir: { frame: '/cosmetics/deck_noir.svg', field: '#0c0b0f', accent: '#c8a35a' },
  back_crimson: { frame: '/cosmetics/deck_crimson.svg', field: '#691d2b', accent: '#c4a060' },
  back_neon: { frame: '/cosmetics/deck_neon.svg', field: '#141436', accent: '#45e6e6' },
  back_kente: { frame: '/cosmetics/deck_kente.svg', field: '#aa5229', accent: '#e2a92e' },
  back_cosmos: { frame: '/cosmetics/deck_cosmos.svg', field: '#060609', accent: '#9a6ae8' },
};

// ─── Table felts (the oval's cloth) ───────────────────────────
// `felt_emerald` is the original green felt. The art felts carry a `frame`:
// a self-contained SVG underlay (procedural rim ornament + base cloth,
// generated by client/scripts/build-cosmetic-decks.mjs into public/cosmetics)
// painted through `--felt-bg` ABOVE the colour gradient — the hi…edge tones
// match the SVG's base so the gradient is a faithful fallback while the
// image decodes (and feeds any colour-only consumers like swatches).
export const TABLE_FELTS = {
  felt_emerald: { hi: '#2f5e3f', mid1: '#245132', mid2: '#18391f', low: '#0e2415', edge: '#0a1a10' },
  felt_wine: { hi: '#5e2f3a', mid1: '#51242f', mid2: '#391820', low: '#240e13', edge: '#1a0a0d' },
  felt_midnight: { hi: '#2f3f5e', mid1: '#243251', mid2: '#182339', low: '#0e1524', edge: '#0a0f1a' },
  felt_ocean: { hi: '#2f5e58', mid1: '#245149', mid2: '#183934', low: '#0e2420', edge: '#0a1a17' },
  felt_noir: { frame: '/cosmetics/felt_noir.svg', hi: '#211d29', mid1: '#14121a', mid2: '#0e0d13', low: '#0b0a0f', edge: '#07060a' },
  felt_crimson: { frame: '/cosmetics/felt_crimson.svg', hi: '#8a2a3c', mid1: '#6b1e2c', mid2: '#581826', low: '#4c1320', edge: '#3a0d18' },
  felt_neon: { frame: '/cosmetics/felt_neon.svg', hi: '#20204c', mid1: '#17173c', mid2: '#131336', low: '#101030', edge: '#0c0c26' },
  felt_kente: { frame: '/cosmetics/felt_kente.svg', hi: '#c06636', mid1: '#a85128', mid2: '#9a4924', low: '#8d4220', edge: '#7a3719' },
  felt_cosmos: { frame: '/cosmetics/felt_cosmos.svg', hi: '#10101e', mid1: '#0a0a14', mid2: '#080810', low: '#06060c', edge: '#06060c' },
};

export const DEFAULT_EQUIPPED = {
  gunSkin: 'gun_steel',
  cardBack: 'back_leather',
  tableFelt: 'felt_emerald',
};

export function gunSkinFor(id) {
  return GUN_SKINS[id] || GUN_SKINS[DEFAULT_EQUIPPED.gunSkin];
}

export function cardBackFor(id) {
  return CARD_BACKS[id] || CARD_BACKS[DEFAULT_EQUIPPED.cardBack];
}

export function tableFeltFor(id) {
  return TABLE_FELTS[id] || TABLE_FELTS[DEFAULT_EQUIPPED.tableFelt];
}

// The CSS custom properties the table styles consume (helpers.js +
// CenterTablePanel + CardHand and friends). Spread onto the OnlinePlayerUI
// root so the viewer's OWN felt + deck skin theme everything below; defaults
// in the CSS keep the original look when no cosmetics are equipped.
//
// Two deck-skin flavours:
//  • CSS-only (leather): gradient stop vars + the gold mini-filigree overlay.
//  • Frame art: --cardback-bg / --cardface-bg point at the skin SVG (which is
//    self-contained — field + ornament), and the filigree overlay is hidden
//    (--cardback-filigree-opacity: 0) so it doesn't fight the artwork.
export function cosmeticStyleVars(equipped) {
  const felt = tableFeltFor(equipped?.tableFelt);
  const back = cardBackFor(equipped?.cardBack);
  const vars = {
    '--felt-hi': felt.hi,
    '--felt-mid1': felt.mid1,
    '--felt-mid2': felt.mid2,
    '--felt-low': felt.low,
    '--felt-edge': felt.edge,
    '--cardback-accent': back.accent,
  };
  // Art felt: the SVG underlay paints over the colour gradient (which stays
  // as the decode-time fallback). `.poker-table-felt` defaults the layer to
  // `none`, so colour-only felts are untouched.
  if (felt.frame) {
    vars['--felt-bg'] = `url("${felt.frame}")`;
  }
  if (back.frame) {
    vars['--cardback-bg'] = `url("${back.frame}")`;
    vars['--cardface-bg'] = `url("${back.frame}")`;
    vars['--cardback-filigree-opacity'] = '0';
  } else {
    vars['--cardback-a'] = back.a;
    vars['--cardback-b'] = back.b;
    vars['--cardback-c'] = back.c;
  }
  return vars;
}
